### ISSUE TITLE
register native routines

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#127]
The new version of R requires registering native routines. See https://stackoverflow.com/questions/42313373/r-cmd-check-note-found-no-calls-to-r-registerroutines-r-usedynamicsymbols

I've implemented this (commit forthcoming), but wanted to run it by @markmfredrickson and @nullsatz. With the changes I've made, it compiles on Rdevel (which is destined to become 3.5) without note or warning.

**Comment by josherrickson** [comment]
See commit 666203d0.

**Comment by josherrickson** [comment]
Along the same lines, running devtools commands in RStudio is forcing changes in RcppExports.R. Committed in 9730c6e. Again, just wanting to run it by the more C-oriented folks.

**Comment by josherrickson** [comment]
Yet another automated change to RcppExports.R. This one required an update to optmatch_init.c too. (This fixes the issue @benthestatistician and I were briefly discussing in #124.) Still not entirely comfortable with what I'm doing here, I'd love to get @markmfredrickson or @nullsatz to chime in to make sure I'm not making a mess of things.

**Comment by josherrickson** [comment]
Just spoke with @nullsatz, he looked over the various changes I've made and didn't spot any concerns. Closing.

**Comment by josherrickson** [comment]
Just to comment, as of the latest commit, we pass all checks on both 3.4 (current) and 3.5 (devel) in Travis.

**Comment by benthestatistician** [comment]
Shortly after @josherrickson 's comment about passing all checks, we stopped passing checks.  Here's the [travis CI page for optmatch](https://travis-ci.org/markmfredrickson/optmatch/builds); Josh's last comment on this thread was around the time of [master b02294c], while as of [master  149e42b] we started having problems. 

These problems are only on R:release and R:devel, not on R:oldrel.  I couldn't immediately see how to interpret these as R version numbers.   Perhaps the issue is that travis mapped them to new versions of R in the meantime?  It's difficult to see how [master  149e42b] could be causing these problems. 

Interestingly, the hinting branch, which hasn't been updated in a while, has issues under R:oldrel but not under R:release or R:devel.  Go figure. 

It may be that these issues are really a new issue, not connected to registration of native routines, but I'm guessing that it isn't, so I'm going to re-open this issue.  Feel free to close out again and reopen something else if you learn something indicating that. (Others whom this may concern: @adamrauh @markmfredrickson .)

**Comment by josherrickson** [comment]
So this is something I ran into before but forgot to follow up on, so thanks for flagging it again. I'm very confident that its unrelated to this issue (and unrelated to the optmatch R package). I'll start a new thread to document to the issue.

**Comment by benthestatistician** [comment]
Thanks, @josherrickson .  I was having a problem building and testing the package locally and I figured it was tied to the problem travis was reporting.  A bit more banging on it is consistent it's having been unrelated to #140.

@adamrauh: I find that on my machine, I am able to install and run tests of either the master or the hinting branch, but only when following a specific sequence of steps. 

In the master branch, 

     $ make clean
     $ R
      > devtools::install()
     > devtools::test()

In addition, to get this to work on the hinting branch, I had to pull in recent updates to the master branch.  I pushed those changes to the hinting branch here on github, so you can get them by updating your fork.   

This was done mostly with R 3.4.1 on x86_64-apple-darwin15.6.0 .  I was able to get it working on evalengin as well, but there the first time I tried `devtools::install()` it didn't work.  but then I got out of R, did 

      $ git checkout -- R/RcppExports.R 
      $ git checkout -- src/RcppExports.cpp 

and then restarted R and ran `devtools::install()` again; that time it worked. First with master branch, then with hinting branch too.
