### ISSUE TITLE
FORTRAN dependency

### ISSUE THREAD

**Issue by markmfredrickson** [markmfredrickson/optmatch#223]
A user was trying to install from github without having to install FORTRAN. This seemed possible since we no longer include the RELAX-IV lib. The obvious thing to do was remove the `$(FLIBS)` in our `Makevars` file, implemented in 8e925cc2a.

But this causes a warning in `check`:

https://github.com/markmfredrickson/optmatch/runs/7379940076?check_suite_focus=true#step:7:16

[This issue from another project](https://github.com/quanteda/quanteda/issues/1524) suggests it is necessary if including BLAS libraries and the guide to writing R extensions includes the same.

I will probably roll back that change, but before I do, I thought I would solicit any feedback people have.

**Comment by josherrickson** [comment]
That's interesting - I'd be curious to see the user error. I'm fairly certain I tested on a system without specifically installing FORTRAN for this specific purpose - but in hindsight I may only have run a check, not actually try to build the package. Alternatively, this may be an OS specific issue, as on Macs, recently installing gcc via homebrew is sufficient to get FORTRAN libraries working (whereas in the past, I'd have to install the stuff directly from R-project).

**Comment by benthestatistician** [comment]
Probably most users who want to do this should just install fortran, in the manner suggested on CRAN.  Another option is to clone or fork the package, then patch src/Makevars with the commit Mark references in the issue statement, [8e925cc](https://github.com/markmfredrickson/optmatch/commit/8e925cc2a238178554004405c6eb902547d319ce).  We've unable to incorporate that change into the package code because of the check warnings it causes.
