### ISSUE TITLE
informative error when distances are outside of integer conversion range

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#230]
Noah Greifer brought an issue to my attention which I currently believe is a bug in MatchIt, but does indicate a need for a better error catch on our end.

```{r}
> d <- match_on(pr ~ cost, data = nuclearplants)
> d@.Data[1] <- 3e14
> fullmatch(d, data = nuclearplants)
Error in as.data.frame.list(x@.Data, col.names = x@names, ...) : 
  trying to get slot "names" from an object (class "EdgeList") that is not an S4 object 
In addition: Warning messages:
1: In doubleSolve(dm, min.cpt, max.cpt, f.ctls, matchable_nodes_info,  :
  NAs introduced by coercion to integer range
2: In class(x) <- tibble_class :
  Setting class(x) to multiple strings ("tbl_df", "tbl", ...); result will no longer be an S4 object
```

Due to that extreme distance value, `as.integer` freaks out at https://github.com/markmfredrickson/optmatch/blob/6255baf527a2e9cd2f3d16f4e925d30f2d8059d5/R/solve_reg_fm_prob.R#L159

```{r}
> as.integer(3e14)
[1] NA
Warning message:
NAs introduced by coercion to integer range 
```

We should be able to catch this at some earlier point and produce a clearer error. At a minimum a `tryCatch` around the call to `as.integer`.

Bigger ideas:
1) Do we still need to cast things to integer when using LEMON? I think not, but I don't have a good sense of the scope of the changes to handle this - is it just adding more conditionals on `solver`, or is the integer assumption baked in in more places?
2) Can we check the distance matrix at an earlier step to ensure there's nothing out of range?

**Comment by benthestatistician** [comment]
If LEMON doesn't require integer distances or prices, then we can modify to avoid casting to integer when LEMON is the solver. We might:
1.  remove the `as.integer()` invocations inside of `doubleSolve()`, 
2. modify the conditional at the beginning of `intSolve()` ([solve_reg_fm_prob.R#L197-L200](https://github.com/markmfredrickson/optmatch/blob/6255baf527a2e9cd2f3d16f4e925d30f2d8059d5/R/solve_reg_fm_prob.R#L197-L200)) so that it doesn't get invoked for the LEMON solver, and 
3. add a similar similar conditional just afterward to recast the distances as integer, but only for RELAX.   

It wouldn't hurt also to 
 4\. add an informative warning in cases of integer overflow, suggesting that the user reduce the tolerance. 

Checking the matrix at an earlier step would be nice but probably exceeds our time budget.

**Comment by josherrickson** [comment]
A quick hack to remove those integer conversions/checks (see below for diff) allows the solver to proceed, albeit with warnings I haven't explored:

```r
> fullmatch(d, data = nuclearplants)
   H    I    A    J    B    K    L    M    C    N    O    P    Q    R    S    T 
 1.3  1.3  1.1  1.2  1.2  1.4 1.10  1.4  1.3  1.6  1.4  1.1  1.1  1.5  1.1  1.1 
   U    D    V    E    W    F    X    G    Y    Z    d    e    f    a    b    c 
 1.6  1.4  1.6  1.5  1.7  1.6  1.7  1.7  1.3  1.6  1.9  1.4  1.8  1.8  1.9 1.10 
Warning messages:
1: In fmatch(dm, max.row.units = ceiling(1/min.cpt), max.col.units = ceiling(max.cpt),  :
  NAs introduced by coercion to integer range
2: In intsol$solution * dm_distance :
  longer object length is not a multiple of shorter object length
```

So this confirms what we believed to be true: LEMON does not require integer distances. Those warnings are pretty concerning so there's more to be done, but this is could be useful.

Regarding `tol`, I'm not sure how it would help in this situation. I tried very varied values of `tol` (without the changes in this post) and never avoided the error.

















Diff of hacky changes to remove integers from distances:

```
diff --git a/R/fmatch.R b/R/fmatch.R
index d348126..921eb45 100644
--- a/R/fmatch.R
+++ b/R/fmatch.R
@@ -72,7 +72,6 @@ fmatch <- function(distance,
                  )# This also removes arcs to/from nodes not in subproblem.
   if (!is.integer(distance[['dist']])) {
       tdist  <- as.integer(distance[['dist']])
-      if (!isTRUE(all.equal(distance[['dist']],tdist))) stop("distance should be integer")
       distance  <- edgelist(tibble::tibble(i=distance[['i']],
                                            j=distance[['j']],
                                            dist=tdist
diff --git a/R/solve_reg_fm_prob.R b/R/solve_reg_fm_prob.R
index 9897ad6..8799f34 100644
--- a/R/solve_reg_fm_prob.R
+++ b/R/solve_reg_fm_prob.R
@@ -156,7 +156,7 @@ doubleSolve <- function(dm, min.cpt, max.cpt, f.ctls, node_info,
                         rfeas, cfeas, epsilon, solver)
 {
     dm_distance  <- dm$'dist' #Used below in roundoff error crude estimate
-    dm$'dist'  <- as.integer(ceiling(.5 + dm$'dist' / epsilon))
+    dm$'dist'  <- ceiling(.5 + dm$'dist' / epsilon)
     if (!is.null(node_info))
         node_info$price  <-
             as.integer(ifelse(abs(node_info$price) <sqrt(.Machine$double.eps),
@@ -194,11 +194,6 @@ doubleSolve <- function(dm, min.cpt, max.cpt, f.ctls, node_info,

 intSolve <- function(dm, min.cpt, max.cpt, f.ctls, node_info, solver) {
   stopifnot(is(dm, "EdgeList"), is(node_info, "NodeInfo"))
-  if (!is.integer(node_info[['price']])) {
-    price_col_position  <- which(node_info@names=="price")
-    node_info@.Data[[price_col_position]]  <-
-      as.integer(round(node_info[['price']]))
-  }
 ```

**Comment by josherrickson** [comment]
Actually, running with either solver produces the same results (a match with concerning errors) so this will require more investigation.

```r
> fullmatch(d, data = nuclearplants, solver = "RELAX-IV")
   H    I    A    J    B    K    L    M    C    N    O    P    Q    R    S    T 
 1.3  1.3  1.1  1.2  1.2  1.4 1.10  1.4  1.3  1.6  1.4  1.1  1.1  1.5  1.1  1.1 
   U    D    V    E    W    F    X    G    Y    Z    d    e    f    a    b    c 
 1.6  1.4  1.6  1.5  1.7  1.6  1.7  1.7  1.3  1.6  1.9  1.4  1.8  1.8  1.9 1.10 
Warning messages:
1: In fmatch(dm, max.row.units = ceiling(1/min.cpt), max.col.units = ceiling(max.cpt),  :
  NAs introduced by coercion to integer range
2: In intsol$solution * dm_distance :
  longer object length is not a multiple of shorter object length
> fullmatch(d, data = nuclearplants, solver = "LEMON")
   H    I    A    J    B    K    L    M    C    N    O    P    Q    R    S    T 
 1.3  1.3  1.1  1.2  1.2  1.4 1.10  1.4  1.3  1.6  1.4  1.1  1.1  1.5  1.1  1.1 
   U    D    V    E    W    F    X    G    Y    Z    d    e    f    a    b    c 
 1.6  1.4  1.6  1.5  1.7  1.6  1.7  1.7  1.3  1.6  1.9  1.4  1.8  1.8  1.9 1.10 
Warning messages:
1: In fmatch(dm, max.row.units = ceiling(1/min.cpt), max.col.units = ceiling(max.cpt),  :
  NAs introduced by coercion to integer range
2: In intsol$solution * dm_distance :
  longer object length is not a multiple of shorter object length
```

**Comment by benthestatistician** [comment]
`fmatch()` appears to cast everything as integer as well (at least on master branch).  That would have to be undone before we get to see whether LEMON really is OK with the non-integer data.

**Comment by benthestatistician** [comment]
I ran into an issue where a solvable matching problem was incorrectly deemed infeasible as an indirect result of `NA`s arising in conversion to integer.  For me the problem also arose in `doubleSolve()`, but a but farther down than in the provided example, at [solve_reg_fm_prob.R#L161-L166](https://github.com/markmfredrickson/optmatch/blob/master/R/solve_reg_fm_prob.R#L161-L166).

I propose that as (¿part of?) a solution we write an internal function `as_integer()`, doing 2 things differently than `as.integer()`:
1. It follow the S behavior rather than the R behavior.  As described on the `as.integer()` help page:
> Real values larger in modulus than the largest integer are coerced to NA (unlike S which gives the most extreme integer of the same sign). 
2. When given a number with modulus larger than `.Machine$integer.max`, it gives an informative warning telling the user to make their distances smaller and/or make their tolerances larger. 
3. When given a number with modulus larger than `.Machine$integer.max`, it also tags its output in a manner indicating that the special conversion has occurred. (So that we can design more informative specific warnings if/as needed.)

**Comment by benthestatistician** [comment]
On further review, this issue traces to a bug on my part, where I wrote `min()` where I meant `max()`.  c6db572 fixes this.  As in the process creates a series of testing failures, I put it on a new branch, i230-integer-conversion.  

The testing failures all have to do with the LEMON solver.  As my bug fix will have the effect of increasing discretization error, I conjecture that what's happening is that the LEMON solver is now solving a sufficiently different integer problem that it's recognizably lacking as a solution to the dual-precision problem.  It would be nice for that not to happen, but it's not really a bug per se if it does, so it would be legitimate to adjust the tests so that they don't fail for this reason.

**Comment by benthestatistician** [comment]
If we'll be pushing a patch to address #233, it would be nice to address this as well. Given my deadlines I can't turn to this at just this moment, however.  Any chance you could help me address the testing failures on the i230-integer-conversion branch, @josherrickson, so possible to fix up this problem with that patch release?

**Comment by josherrickson** [comment]
@benthestatistician Do you have thoughts on how to address this? Should we add some sort of threshold for equivalency? E.g. something like `all.equal(..., ..., tolerance = .05, scale = 1)`? Or do we need to look further into addressing whether the test failures is an actual error?

**Comment by josherrickson** [comment]
Also, to be explicit, Ben's fix does address the issue:

```r
> d <- match_on(pr ~ cost, data = nuclearplants)
> d@.Data[1] <- 3e14
> fullmatch(d, data = nuclearplants)
   H    I    A    J    B    K    L    M    C    N    O    P    Q    R    S    T    U    D 
1.10 1.10  1.1 1.10  1.2 1.10 1.10 1.10  1.3 1.10 1.10 1.10 1.10 1.10 1.10 1.10  1.9  1.4 
   V    E    W    F    X    G    Y    Z    d    e    f    a    b    c 
 1.8  1.5  1.7  1.6  1.6  1.7  1.5  1.4  1.3  1.2  1.1  1.8  1.9 1.10 
```

**Comment by benthestatistician** [comment]
I agree about relaxing the threshold for solution optimality, where that passes the test.  In other cases the tests can be made to pass by adjusting the `tol` argument to `pairmatch()` or `fullmatch()`. I was able to quell the problems in test.complementarySlackness.R in this way, see i230-integer-conversion dc3930a.  At least some of the remaining test failure problems can be addressed in a similar way.

**Comment by josherrickson** [comment]
I think most of the remaining issues are due to our tests being too strict; I switched to weaker forms of equivalence and all tests now pass.

**Comment by josherrickson** [comment]
Branch i230-integer-conversion is now in master. @benthestatistician I added to the news, https://github.com/markmfredrickson/optmatch/blob/c92a275ee2afb3578f10fbe21b046b111fc64578/NEWS.md?plain=1#L6-L7, feel free to update if you want to.
