### ISSUE TITLE
Merging optmatch objects

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#68]
`optmatch` objects should be able to be merged easily. Overriding `c()` seems the most natural, as `optmatch` objects are essentially `factor` objects with extra information.

**Comment by benthestatistician** [comment]
I'm not sure overriding `c()` is the way to go, partly b/c `c()` doesn't do anything helpful for factors:
```{r}
> fac1 = factor(letters[1:3]); fac2 = factor(letters[2:4])
> fac1
[1] a b c
Levels: a b c
> fac2
[1] b c d
Levels: b c d
> c(fac1, fac2)
[1] 1 2 3 1 2 3
```
Perhaps we should reduce our sights from handling this operation with a single nifty command...

**Comment by benthestatistician** [comment]
Alternate proposal: provide methods to coerce optmatch objects to and from data frames, along with examples showing how to use them to merge optmatch objects. 

The data frames that optmatch objects get converted to might contain both the original optmatch object as-is, and additional columns for: the treatment variable, exact matching variables used in the match, etc.   Perhaps there could be special names, or name-patterns, associated with these columns to indicate which was which, in which case the method to back-convert a data frame to an optmatch object would require columns with names matching the appropriate patterns for the treatment variable and the matching categories.  (And, if it found those, look around for columns to interpret as exact matching categories, etc.)    Then one could merge two optmatch objects using e.g.
```{r}
as.optmatch( rbind( as.data.frame(optmatch1), as.data.frame(optmatch2) ) )
```
Note that `rbind`, in contrast to `c()`, is set up to properly combine factors.

**Comment by benthestatistician** [comment]
@josherrickson do you have thoughts or suggestions regarding the last proposal I made on this thread (20 months ago now)? 

Thinking of this after email I copied you on from Mike Baiocchi and Joe Rigdon, who want to stitch together matching results after farming out subproblems to different nodes of a cluster.  If we could wrap this discussion up into a clear set of next steps, then one of us (or them) could more readily knock this task off, and that would be a nice first step toward supporting the usage they're planning.

**Comment by benthestatistician** [comment]
@adamrauh the discussion about possible evolution of optmatch data structure is on this thread.  (Context: If we're going to be adding in node price data anyway, perhaps we should go ahead and give the entire specification of optmatch objects a facelift, while we're at it.)

Observation: In order to be able to store node prices in a vector aligned with the factor object encoding the match, it needs to be the case that the prices of treatment and control nodes, but not End or Overflow nodes, constitute a "sufficient statistic" for a solution to the dual problem being addressed by the solver.  (A. & I discussed a mathematical conjecture from which this would follow, namely a conjecture that one can articulate an algorithm for deducing End and Overflow prices from those of remaining nodes that will gives a set of node prices in a CS relationship with a given feasible flow if there exists any pair of (End, Overflow) prices which when joined with the given T and C node prices is in a CS relationship with the same feasible flow.)

**Comment by benthestatistician** [comment]
- Reviewing comments on this thread, I may have diverted conversation into an unhelpful direction some time back.  My concern that `c()` doesn't apply well to factor objects is beside the point; we could define a `c.optmatch` S3 method that fixes that.  I'd like to retract that comment and go back to consideration of Josh's proposal to override `c()`. 
- But rather than overriding with an S3 method, it'd be better to define an S4 method accommodating the new Optmatch class introduced by @adamrauh ; see issue54-hinting branch , R/OptmatchS4.R.

**Comment by josherrickson** [comment]
I realized that I haven't responded to a call for comment from 2 years ago...

I threw this together quickly as a proof of concept. I'm sure there's a few other attributes I haven't accounted for.

```
c.optmatch <- function(...) {
  objs <- list(...)
  for (i in 1:length(objs)) {
    levels(objs[[i]]) <- paste0(i, ".", levels(objs[[i]]))
    levels(attr(objs[[i]], "subproblem")) <-
      paste0(i, ".", levels(attr(objs[[i]], "subproblem")))
  }
  out <- unlist(objs)
  class(out) <- c("optmatch", "factor")
  for (a in c("contrast.group", "subproblem")) {
    attr(out, a) <- unlist(sapply(objs, function(x) attr(x, a)))
  }
  out
}
```

```
> f1 <- fullmatch(pr ~ cost, data = nuclearplants[nuclearplants$pt == 1,])
> f2 <- fullmatch(pr ~ cost, data = nuclearplants[nuclearplants$pt == 0,])
> c(f1, f2)
    d     e     f     a     b     c     H     I     A     J     B     K 
1.1.2 1.1.1 1.1.3 1.1.1 1.1.2 1.1.3 2.1.3 2.1.3 2.1.1 2.1.2 2.1.2 2.1.4 
    L     M     C     N     O     P     Q     R     S     T     U     D 
2.1.4 2.1.4 2.1.3 2.1.6 2.1.4 2.1.1 2.1.1 2.1.5 2.1.1 2.1.1 2.1.6 2.1.4 
    V     E     W     F     X     G     Y     Z 
2.1.6 2.1.5 2.1.7 2.1.6 2.1.7 2.1.7 2.1.3 2.1.6 
> summary(c(f1, f2))
Structure of matched sets:
1:1 1:2 1:3 1:4 
  5   1   1   3 
Effective Sample Size:  12.6 
(equivalent number of matched pairs).

> attr(c(f1, f2), "subproblem")
  d   e   f   a   b   c   H   I   A   J   B   K   L   M   C   N   O   P   Q 
1.1 1.1 1.1 1.1 1.1 1.1 2.1 2.1 2.1 2.1 2.1 2.1 2.1 2.1 2.1 2.1 2.1 2.1 2.1 
  R   S   T   U   D   V   E   W   F   X   G   Y   Z 
2.1 2.1 2.1 2.1 2.1 2.1 2.1 2.1 2.1 2.1 2.1 2.1 2.1 
Levels: 1.1 2.1
```

**Comment by benthestatistician** [comment]
Nice.  One attribute that will become important is "MCFSolutions", currently only in the issue54-hinting branch.   That branch already provides a `c()` method for those objects.

**Comment by josherrickson** [comment]
The version in branch issue68-c retains all attributes. 
- `levels`, `names`, `contrast.group`, `subproblem` vectors are all `c'`d appropriately.
- `class` is unchanged
- `min.controls`, `max.controls`, `omit.fraction` and `exceedances` are named vectors, similar to attributes of BISM's (`c.optmatch` works with BISM's just fine as well).
- `call` and `hashed.distance` are lists; `update.optmatch` has been modified to error if a `c`'d Optmatch object is passed to it.

`print.optmatch` works fine; any suggestions on formal tests for it? Just ensure it's not erroring?

**Comment by benthestatistician** [comment]
Nice! Re test for print.optmatch, how about trying out testthat's
`expect_output_file()`, as suggested [in this blog post](
https://blog.rstudio.com/2016/04/29/testthat-1-0-0/).

>

**Comment by josherrickson** [comment]
I'm hesitant to use that (FYI, it's been renamed to `expect_known_output` since that post) because it gets us back to where we were pre-testthat with all those .Rout files.

I've added a few tests using `expect_output` which I think is sufficient.
